abstract: Validate Japanese phone numbers
author: Koichi Taniguchi <taniguchi@livedoor.jp>
build_requires: 
  Test::More: 0
distribution_type: module
generated_by: Module::Install version 0.64
license: perl
name: Number-Phone-JP
no_index: 
  directory: 
    - inc
    - t
requires: 
  UNIVERSAL::require: 0
version: 0.10
