use strict;
use Test::More tests => 10;
use_ok('Number::Phone::JP');
use_ok('Number::Phone::JP', qw(home));
use_ok('Number::Phone::JP', qw(home mobile));
use_ok('Number::Phone::JP', qw(mobile phs));
use_ok('Number::Phone::JP', qw(phs freedial));
use_ok('Number::Phone::JP', qw(freedial q2));
use_ok('Number::Phone::JP', qw(q2 ipphone));
use_ok('Number::Phone::JP', qw(ipphone pager));
use_ok('Number::Phone::JP', qw(pager class1));
use_ok('Number::Phone::JP', qw(class1 class2));
